enum TaskStatus {
  TO_DO
  IN_PROGRESS
  COMPLETED
}

type Task {
  id: ID!
  title: String!
  description: String
  priority: Boolean! 
  deadline: String
  status: TaskStatus!
  boardId: String!
}

type Board {
  id: ID!
  name: String!
  Tasks: [Task!]!
}

type Query {
  boards: [Board]
  tasks: [Task]
}

input taskInput {
  title: String!
  description: String
  priority: Boolean!
  deadline: String
  status: TaskStatus!
}

input boardInput {
  name: String!
}

type Mutation {
  createBoard(data: boardInput): Board!
  createTask(data: taskInput): Task!
}

schema {
  query: Query
  mutation: Mutation
}
